FROM clearlinux/node

WORKDIR /app/

ENV PATH /app/node_modules/.bin:$PATH

RUN swupd bundle-add git
RUN npm install npm yarn -g

RUN git clone https://github.com/medusajs/admin medusa-admin

WORKDIR /app/medusa-admin/

RUN yarn install && yarn cache clean

ENV MEDUSA_BACKEND_URL=http://backend:9000

HEALTHCHECK --interval=10s \
  CMD ["curl", "--request GET", "--fail", "http://localhost:7000", "-I", "|", "exit 0"]

EXPOSE 7000

ENTRYPOINT yarn start
