# FROM node:18.12.1
FROM clearlinux/node

WORKDIR /app/

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install npm yarn -g

RUN yarn create next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-storefront
RUN yarn cache clean

WORKDIR /app/my-medusa-storefront/
RUN mv .env.template .env.local

COPY entrypoint-frontend.sh .
RUN chmod +x entrypoint-frontend.sh

ENV NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://backend:9000

HEALTHCHECK --interval=10s \
  CMD curl --request GET --fail http://localhost:8080 -I | exit 0

EXPOSE 8080

ENTRYPOINT ["./entrypoint-frontend.sh"]
